AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  Max: 100

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/ExpandPathArguments:
  Exclude:
    - cartafact_rb.gemspec

Style/StringLiterals:
  Enabled: false