AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  Max: 100

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/EmptyLiteral:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - cartafact_rb.gemspec

Style/StringLiterals:
  Enabled: false